apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret-placeholder.yaml

  - rabbitmq.yaml

  - core.yaml
  - auth.yaml
  - auth-web.yaml
  - apigate.yaml
  - comdash.yaml
  - erp-proxy.yaml

  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: erpq


